In [87]:
import json
import pandas as pd
import pickle

We start by processing the card list.

In [116]:
with open('all_cards.pkl', 'rb') as f:
  all_cards = pickle.load(f)
df_cards = pd.DataFrame(all_cards)
print(f'Loaded {df_cards.shape[0]} cards')

Loaded 265 cards

On `arkhamdb`, a large number of decklists only have cards from the Core or Revised Core set, since that is the entry point into the game. The next largest group of decklists selects cards from the Core and Dunwich Legacy expansion, followed by decklists that go up to Path to Carcosa, etc., following the chronological order the expansions were released.

Because of this, if we tallied up all the cards used in all the decklists, the count will be biased toward the Core set cards and away from cards from the more recent expansions. But just because the most common gun used by Guardians is the .45 Automatic doesn't mean it's the best gun for each of Guardian investigator.

`rangersdb` decks follow this pattern so far, with most decks using just the Core set followed by decks that also draw from Stewards of the Valley. To account for this bias, here we define the order of Earthborne Ranger packs, which is what `rangersdb` calls them, and create some helper dictionaries.

In [117]:
PACK_ORDER = [
  'core',  # Core set
  'sotv',  # Stewards of the Valley
  'loa'    # Legacy of the Ancestors
]
PACK_TO_INDEX = {pack_id: i for i, pack_id in enumerate(PACK_ORDER)}
INDEX_TO_PACK = {i: pack_id for i, pack_id in enumerate(PACK_ORDER)}
df_cards["card_pack_index"] = df_cards["pack_id"].map(PACK_TO_INDEX)
card_id_to_pack_index = (df_cards
  .set_index("id")
  .to_dict()["card_pack_index"])
card_id_to_name = (df_cards
  .set_index("id")
  .to_dict()["name"])
print('Count cards in each pack:')
df_cards.groupby("card_pack_index").size()

Count cards in each pack:

card_pack_index
0    155
1     81
2     29
dtype: int64

Note that this reports 155 cards in the Core set when it actually contains 140. This is because it contains new versions of cards from [The Elder's Book of Uncommon Wisdom](https://thelivingvalley.earthbornegames.com/docs/updates/elders_book_of_uncommon_wisdom/), which is sometimes used to nerf overpowered cards. Many decks have not updated to the new version of cards, and maybe the player wouldn't include the newer version of the card. Here, we label each card `id` if it is or isn't their latest version.

In [118]:
# These cards id were enhanced in taboo set_01, so if the user liked the older
# version, they would also like the newer version
NOT_NERFED = ('01041', '01044', '01069', '01074', '01084')
# taboo_id is None for the original version of each card
df_cards["taboo_fill_id"] = df_cards["taboo_id"].fillna('set_00')
df_cards["latest_taboo_id"] = (df_cards
  .groupby("code")["taboo_fill_id"]
  .transform("max"))
df_cards["is_latest"] = (
  (df_cards["taboo_fill_id"] == df_cards["latest_taboo_id"])
  | df_cards["id"].isin(NOT_NERFED))

print('Latest cards in each pack:')
df_cards.groupby("card_pack_index").agg(
  latest=("is_latest", "sum"),
  not_latest=("is_latest", lambda x: (~x).sum()))

Latest cards in each pack:

                 latest  not_latest
card_pack_index
0                   145          10
1                    81           0
2                    29           0

Each deck has `set_type_id` and `set_id` attributes, but they are not quite the way we want to group cards:

In [119]:
(df_cards[["set_type_id", "set_id"]]
  .drop_duplicates()
  .sort_values(by=["set_type_id", "set_id"]))

    set_type_id          set_id
20   background         artisan
28   background         forager
10   background        shepherd
184  background     talespinner
11   background        traveler
8     specialty       artificer
1     specialty     conciliator
4     specialty        explorer
0     specialty          shaper
188   specialty  spirit_speaker
2          None          malady
58         None     personality
3          None          reward

Players make eight different card selections during deck creation: their Role, the four Personality aspects, their Background cards, their Specialty cards, and their Outside Interest. So we modify `set_type_id` and `set_id` into the `supergroup_id` and `subgroup_id`, which groups cards for these eight choices.

In [120]:
def get_supergroup_id(card):
  if card["set_id"] == 'personality':
    return 'Personality'
  set_type_id = card["set_type_id"]
  if set_type_id == 'specialty' and card["type_id"] == 'role':
    return 'Role'
  return (set_type_id.capitalize()
          if isinstance(set_type_id, str) else set_type_id)

def get_subgroup_id(card):
  if card["set_id"] == "personality":
    return card["aspect_name"].title()
  return card["set_id"].replace('_', ' ').title()

df_cards["supergroup_id"] = df_cards.apply(get_supergroup_id, axis=1)
df_cards["subgroup_id"] = df_cards.apply(get_subgroup_id, axis=1)

print('Supergroup and subgroup combinations:')
(df_cards[["supergroup_id", "subgroup_id"]]
  .drop_duplicates()
  .sort_values(by=["supergroup_id", "subgroup_id"]))

Supergroup and subgroup combinations:

    supergroup_id     subgroup_id
20     Background         Artisan
28     Background         Forager
10     Background        Shepherd
184    Background     Talespinner
11     Background        Traveler
63    Personality       Awareness
58    Personality         Fitness
61    Personality           Focus
62    Personality          Spirit
54           Role       Artificer
132          Role     Conciliator
56           Role        Explorer
55           Role          Shaper
234          Role  Spirit Speaker
8       Specialty       Artificer
1       Specialty     Conciliator
4       Specialty        Explorer
0       Specialty          Shaper
188     Specialty  Spirit Speaker
2            None          Malady
3            None          Reward

That's all the preprocessing we need to do for the cards, now let's load the decks.

In [123]:
with open('decks.pkl', 'rb') as f:
  all_decks = pickle.load(f)
print(f'Loaded {len(all_decks)} decks between {min(all_decks.keys())} and {max(all_decks.keys())}')
decks_clean = [deck for deck in all_decks.values() if deck is not None]
df_all_decks = pd.DataFrame(decks_clean)
df_all_decks["taboo_set_id"] = df_all_decks["taboo_set_id"].fillna('set_00')
print(f'Loaded {df_all_decks.shape[0]} non-blank decks between {df_all_decks["id"].min()} annd {df_all_decks["id"].max()}')

Loaded 25146 decks between 1 and 25146
Loaded 14352 non-blank decks between 1 annd 25117

Each deck stores their Background, Specialty, and Role in the `meta` attribute. Here, we move them into their own columns, and we ignore some malformed decks that don't have all three.

In [124]:
def extract_background(meta):
  return meta.get("background", None)
def extract_specialty(meta):
  return meta.get("specialty", None)
def extract_role_id(meta):
  return meta.get("role", None)

df_all_decks["background"] = df_all_decks["meta"].apply(extract_background)
df_all_decks["specialty"] = df_all_decks["meta"].apply(extract_specialty)
df_all_decks["role_id"] = df_all_decks["meta"].apply(extract_role_id)

df_all_decks["is_ignore"] = (
  df_all_decks["background"].isna()
  | df_all_decks["specialty"].isna()
  | df_all_decks["role_id"].isna())
ignore_count = df_all_decks["is_ignore"].sum()
print(f'Ignored decks: {ignore_count}')

Ignored decks: 36

We want to look at decks that players made, so we ignore decks that are identical to the [premade decks](https://earthbornegames.com/resources/ranger-decks).

In [125]:
#| include: false
# ignore pre-built decks
def card_name_to_ids(name):
  return df_cards.loc[
    (df_cards["name"] == name),
    "id"
  ].tolist()

UNDAUNTED_SEEKER = {
  'background': 'traveler',
  'specialty': 'explorer',
  'role_id': card_name_to_ids('Undaunted Seeker'),
  'awa': 2,
  'spi': 2,
  'fit': 3,
  'foc': 1,
  'slots': (
    card_name_to_ids('Meticulous'),
    card_name_to_ids('Determined'),
    card_name_to_ids('Insightful'),
    card_name_to_ids('Persuasive'),
    card_name_to_ids('Eagle Eye'),
    card_name_to_ids('Ironwool Boots'),
    card_name_to_ids('Perfect Recall'),
    card_name_to_ids('Reverb Locket'),
    card_name_to_ids('Strider'),
    card_name_to_ids('Afforded by Nature'),
    card_name_to_ids('A Leaf in the Breeze'),
    card_name_to_ids('Boundary Sensor'),
    card_name_to_ids('Orlin Hiking Stave'),
    card_name_to_ids('Walk With Me'),
    card_name_to_ids('Trail Markers'),
  )
}

VOICE_OF_THE_ELDERS = {
  'background': 'shepherd',
  'specialty': 'conciliator',
  'role_id': card_name_to_ids('Voice of the Elders'),
  'awa': 1,
  'spi': 3,
  'fit': 2,
  'foc': 2,
  'slots': (
    card_name_to_ids('Engaging'),
    card_name_to_ids('Astute'),
    card_name_to_ids('Passionate'),
    card_name_to_ids('Perceptive'),
    card_name_to_ids('Calming Presence'),
    card_name_to_ids('Healing Touch'),
    card_name_to_ids('Homeward Bound'),
    card_name_to_ids('Oru the Sheep Dog'),
    card_name_to_ids('Paratrepsis Whistle'),
    card_name_to_ids('A Dear Friend'),
    card_name_to_ids('Follow in Footsteps'),
    card_name_to_ids('Intention Translator'),
    card_name_to_ids('Pokodo the Ferret'),
    card_name_to_ids('Surveyed Land'),
    card_name_to_ids('Energized Hiking Greaves'),
  )
}

MASTERFUL_ENGINEER = {
  'background': 'artisan',
  'specialty': 'artificer',
  'role_id': card_name_to_ids('Masterful Engineer'),
  'awa': 2,
  'spi': 2,
  'fit': 1,
  'foc': 3,
  'slots': (
    card_name_to_ids('Balanced'),
    card_name_to_ids('Inventive'),
    card_name_to_ids('Thorough'),
    card_name_to_ids('Compassionate'),
    card_name_to_ids('Favorite Gear'),
    card_name_to_ids('Functional Replica'),
    card_name_to_ids('Moment of Desperation'),
    card_name_to_ids('Pocketed Belt Pouch'),
    card_name_to_ids('Universal Power Cells'),
    card_name_to_ids('A Stone in the River'),
    card_name_to_ids('Ferinodex'),
    card_name_to_ids('Infusion Canteen'),
    card_name_to_ids('Memorill Sketchpad'),
    card_name_to_ids('Memlev Trekking Poles'),
    card_name_to_ids('Adaptable Multitool'),
  )
}

ADHERENT_OF_THE_FIRST_IDEAL = {
  'background': 'forager',
  'specialty': 'shaper',
  'role_id': card_name_to_ids('Adherent of the First Ideal'),
  'awa': 3,
  'spi': 1,
  'fit': 2,
  'foc': 2,
  'slots': (
    card_name_to_ids('Bold'),
    card_name_to_ids('Thoughtful'),
    card_name_to_ids('Versatile'),
    card_name_to_ids('Vigilant'),
    card_name_to_ids('Familiar Ground'),
    card_name_to_ids('Green Thumb'),
    card_name_to_ids('Local Fare'),
    card_name_to_ids('Loose-Leaf Tea Kit'),
    card_name_to_ids("Nature's Abundance"),
    card_name_to_ids('Root Snare'),
    card_name_to_ids('Shape the Earth'),
    card_name_to_ids('Sky Whip'),
    card_name_to_ids('Stave of the Sun'),
    card_name_to_ids('What Should Never Be'),
    card_name_to_ids('Harmonize'),
  )
}

CARTOGRAPHER_OF_MANY_WORLDS = {
  'background': 'talespinner',
  'specialty': 'spirit_speaker',
  'role_id': card_name_to_ids('Cartographer of Many Worlds'),
  'awa': 1,
  'spi': 2,
  'fit': 2,
  'foc': 3,
  'slots': (
    card_name_to_ids('Dauntless'),
    card_name_to_ids('Enthusiastic'),
    card_name_to_ids('Ingenious'),
    card_name_to_ids('Sensible'),
    card_name_to_ids('Wonders of the Valley'),
    card_name_to_ids('The Buck and the Wolhund'),
    card_name_to_ids('Book of Great Deeds'),
    card_name_to_ids('The Tireless Artisan'),
    card_name_to_ids('Songweave Mantle'),
    card_name_to_ids('Irix Spirit'),
    card_name_to_ids('The Path Opens Before Me'),
    card_name_to_ids('Atrox Spirit'),
    card_name_to_ids('The Long Walk'),
    card_name_to_ids('Lutrinal Spirit'),
    card_name_to_ids('Piercing Whistle'),
  )
}

def if_match_deck(deck, premade):
  for key, value in premade.items():
    if key == 'role_id':
      if deck['role_id'] not in value:
        return False

    elif key == 'slots':
      flatten_slots = [id for id_list in value for id in id_list]
      for card_id in deck['slots']:
        if card_id not in flatten_slots:
          return False

    elif deck[key] != value:
      return False

  return True

df_all_decks["is_ignore"] = (
  df_all_decks["is_ignore"]
  | df_all_decks.apply(lambda deck: if_match_deck(deck, UNDAUNTED_SEEKER), axis=1)
  | df_all_decks.apply(lambda deck: if_match_deck(deck, VOICE_OF_THE_ELDERS), axis=1)
  | df_all_decks.apply(lambda deck: if_match_deck(deck, MASTERFUL_ENGINEER), axis=1)
  | df_all_decks.apply(lambda deck: if_match_deck(deck, ADHERENT_OF_THE_FIRST_IDEAL), axis=1)
  | df_all_decks.apply(lambda deck: if_match_deck(deck, CARTOGRAPHER_OF_MANY_WORLDS), axis=1)
)
ignore_count = df_all_decks["is_ignore"].sum()
print(f'\nIgnored decks: {ignore_count}')

Ignored decks: 885

Now, we start analyzing the cards in each deck.

We assign each deck a `deck_pack_index` reflecting the highest `card_pack_index` among its cards. The reasoning here is, for example, if a deck contains a card from Stewards of the Valley, we assume the player considered all of the cards available up through Stewards of the Valley when choosing cards. So we want to identify and favor decks that consider more cards.

We also count the total equip value of the cards in the deck to get a sense of how much gear a typical deck has.

We also want to ignore decks that don't meed the following conditions:
- They have 15 cards
- None of the cards are spoilers, since cards with `spoiler` are cards like Rewards or Maladies that aren't included in starting decks

In [126]:
def check_cards(deck):
  slots = [card_id for card_id in deck["slots"].keys()]
  has_15_cards = (len(slots) == 15)
  # decks have a 16th card, their role card
  slots.append(deck["role_id"])
  cards = df_cards[df_cards["id"].isin(slots)]
  deck_pack_index = cards["card_pack_index"].max()
  equip_sum = cards["equip"].sum()
  has_spoiler = cards["spoiler"].any()
  is_latest = cards["is_latest"].all()
  return pd.Series({
    "deck_pack_index": deck_pack_index,
    "equip_sum": equip_sum,
    "has_15_cards": has_15_cards,
    "has_spoiler": has_spoiler,
    "is_latest": is_latest
  })

card_check = df_all_decks.apply(check_cards, axis=1)
# Drop columns so running this cell repeatedly doesn't throw an error
for col in card_check.columns:
  if col in df_all_decks.columns:
    print(f'Dropping column {col}')
    df_all_decks = df_all_decks.drop(columns=[col])
df_all_decks = pd.concat([df_all_decks, card_check], axis=1)
df_all_decks["deck_pack_index"] = (df_all_decks["deck_pack_index"]
  .astype('Int64'))

print(f"\ndeck_pack_index distribution:")
for deck_pack_index in range(len(PACK_ORDER)):
  pack_id = INDEX_TO_PACK[deck_pack_index]
  count = (df_all_decks["deck_pack_index"] == deck_pack_index).sum()
  print(f"  {pack_id} (index {deck_pack_index}): {count} decks")

df_all_decks["is_ignore"] = (
  df_all_decks["background"].isna()
  | df_all_decks["specialty"].isna()
  | df_all_decks["role_id"].isna()
  | ~df_all_decks["has_15_cards"]
  | df_all_decks["has_spoiler"]
  # | df_all_decks["is_latest"]
)
ignore_count = df_all_decks["is_ignore"].sum()
print(f'\nIgnored decks: {ignore_count}')

deck_pack_index distribution:
  core (index 0): 11034 decks
  sotv (index 1): 3130 decks
  loa (index 2): 184 decks

Ignored decks: 4618

Decks can have a lineage, having been derived from a `previous_deck` or `original_deck`. We will want to know the parent for all decks, even the ignored decks.

In [127]:
def get_all_decks_parent_id(all_decks_row):
  if all_decks_row["previous_deck"] is not None:
    previous_id = all_decks_row["previous_deck"]["id"]
    # Sometimes the previous deck has been deleted
    if previous_id in df_all_decks["id"].values:
      return previous_id

  if all_decks_row["original_deck"] is not None:
    original_id = all_decks_row["original_deck"]["deck"].get("id", None)
    if original_id in df_all_decks["id"].values:
      return original_id

  return None

df_all_decks["all_decks_parent_id"] = (df_all_decks
  .apply(get_all_decks_parent_id, axis=1)
  .astype('Int64'))
assert (set(df_all_decks["all_decks_parent_id"].dropna())
  <= set(df_all_decks["id"]))
num_parent = df_all_decks["all_decks_parent_id"].notna().sum()
num_all_decks = df_all_decks.shape[0]
print(f'Number of parent_id: {num_parent} out of {num_all_decks} decks')

Number of parent_id: 4468 out of 14352 decks

This new DataFrame only contains the non-ignored decks.

In [128]:
df_decks = df_all_decks[~df_all_decks["is_ignore"]].copy()
print(f'{df_decks.shape[0]} non-ignored decks')

9734 non-ignored decks

Continuing to analyze deck lineage, we also want to find the nearest ancestor that is not ignored, i.e., is also in `df_decks`.

In [129]:
def get_parent_id(deck):
  current_id = deck["all_decks_parent_id"]
  while pd.notna(current_id):
    if current_id in df_decks["id"].values:
      return current_id
      
    current_deck = df_all_decks[df_all_decks["id"] == current_id].iloc[0]
    current_id = current_deck["all_decks_parent_id"]

  return None

df_decks["parent_id"] = (df_decks
  .apply(get_parent_id, axis=1)
  .astype('Int64'))
assert set(df_decks["parent_id"].dropna()) <= set(df_decks["id"])
num_parent = df_decks["parent_id"].notna().sum()
num_decks = df_decks.shape[0]
print(f'Number of parent_id: {num_parent} out of {num_decks} decks')

Number of parent_id: 1262 out of 9734 decks

Later, we'll also use the nearest ancestor in `df_decks` that comes from a different user, which we'll call its `inspiration_id`.

In [130]:
def get_inspiration_id(deck):
  this_user_id = deck["user_id"]
  current_id = deck["parent_id"]
  while pd.notna(current_id):
    current_deck = df_decks[df_decks["id"] == current_id].iloc[0]
    current_user_id = current_deck["user_id"]
    if current_user_id != this_user_id:
      return current_id
      
    current_id = current_deck["parent_id"]

  return None

df_decks["inspiration_id"] = (df_decks
  .apply(get_inspiration_id, axis=1)
  .astype('Int64'))
num_inspiration = df_decks["inspiration_id"].notna().sum()
num_decks = df_decks.shape[0]
print(f'Number of inspiration_id: {num_inspiration} out of {num_decks} decks')

Number of inspiration_id: 672 out of 9734 decks

Now is where we get more subjective.
- For every `user_id`, first we ignore any deck `id` that is a `parent_id` for one of their own decks. The idea is the user has created an improved version of the parent deck, so we ignore the parent deck in favor of the child deck.
- Then, for each `["background", "specialty"]` combination the user made decks for, they are allocated 1 total `user_weight`, divided equally between those decks. So if the user made a bunch of very similar decks, those decks only get one vote split among all of them.

In [131]:
# Identify decks with non-zero user_weight
user_parent_ids = (df_decks.groupby("user_id")["parent_id"]
  .apply(lambda parents: set(parents.dropna())))
df_decks["user_weight"] = (df_decks
  .apply(lambda row: row["id"] not in user_parent_ids[row["user_id"]], axis=1)
  .astype('Int64'))

# Divide 1 user_weight among (user_id, background, specialty) decks
sum_weights = (df_decks
  .groupby(["user_id", "background", "specialty"])["user_weight"]
  .transform("sum"))
df_decks["user_weight"] = (df_decks["user_weight"]
  / sum_weights.where(sum_weights > 0, 1))

user_weight_sum = df_decks["user_weight"].sum()
user_weight_size = (df_decks["user_weight"] > 0).size
print(f'{user_weight_sum} total user_weight split among {user_weight_size} decks')

6832.0 total user_weight split among 9734 decks

Now, if a deck was inspired by another user's deck, the `user_weight` of the child deck is split between it and its inspiration. If the deck wasn't inspired by another user's deck, it keeps all of its `user_weight`. In this way, a higher `deck_weight` reflects more players who liked this deck and made their own versions.

In [132]:
# Decks with no inspiration keep their full user_weight
# Decks with inspiration donate half their user_weight
from_self = df_decks.apply(lambda row: 0.5 * row["user_weight"]
  if pd.notna(row["inspiration_id"]) else row["user_weight"], axis=1)

# Decks receive half the user_weight of decks they inspired
df_inspired = df_decks[df_decks["inspiration_id"].notna()]
sum_weights = df_inspired.groupby("inspiration_id")["user_weight"].sum()
from_inspired = df_decks["id"].map(lambda x: 0.5 * sum_weights.get(x, 0))

df_decks["deck_weight"] = from_self + from_inspired

deck_weight_sum = df_decks["deck_weight"].sum()
deck_weight_size = (df_decks["deck_weight"] > 0).size
print(f'{deck_weight_sum} total deck_weight split among {deck_weight_size} decks')

6832.0 total deck_weight split among 9734 decks

We will penalize decks that haven't adopted the taboo proportional to the decks who have adopted it.

In [133]:
taboo_counts = {taboo_id: (df_decks["taboo_set_id"] <= taboo_id).sum()
  for taboo_id in df_decks["taboo_set_id"].unique()}
max_taboo_count = max(taboo_counts.values())
map_taboo_weight = {taboo_id: float(count / max_taboo_count)
  for taboo_id, count in taboo_counts.items()}
df_decks["taboo_weight"] = df_decks["taboo_set_id"].map(map_taboo_weight)
print(f"Taboo weights: {map_taboo_weight}")
df_decks["group_score"] = df_decks["deck_weight"] * df_decks["taboo_weight"]

Taboo weights: {'set_00': 0.8914115471543045, 'set_01': 1.0}

Let's analyze which (Background, Specialty) combinations are the most popular(*). Each deck contributes its `deck_weight` to its (Background, Specialty) score.

However, this raw total score is pretty biased. The Core set has been around longer, so there has been more time to make decks using only the Core set. And as mentioned earlier, more players have access to the Core set than expansion packs.

So for each `pack_index`, we calculate its average score, as if we were dividing the total score awarded in that `pack_index` equally among the various options. Then for each option, we add up its score over the set of `pack_index` when it is available. We do the same for the average score. Comparing the option's total score to the average score gives us a popularity rating.

(*) For my arbitrary definition of popular.

In [134]:
def group_and_score(df, groupby_cols, score_col, pack_index_col,
    background=None, specialty=None):
  # filter by background and specialty if provided
  if background and specialty:
    df = df[
      (df["Background"] == background)
      & (df["Specialty"] == specialty)
    ]
  # for each (group, pack), total score
  df_group_pack = (df
    .groupby(groupby_cols + [pack_index_col])[score_col]
    .sum()
    .reset_index())
  # for each pack, average score per group
  df_pack_map = (df_group_pack
    .groupby(pack_index_col)[score_col]
    .mean()
    .to_dict())
  # for each (group, pack), add average score per group based on pack
  df_group_pack["pack_avg"] = df_group_pack[pack_index_col].map(df_pack_map)
  # for each group, total score and average score over all its packs
  df_group = (df_group_pack
    .groupby(groupby_cols)[[score_col, "pack_avg"]]
    .sum()
    .reset_index())
  # compare group's score to average group's score
  df_group["score"] = df_group[score_col] / df_group["pack_avg"]
  return df_group.sort_values("score", ascending=False)

In [135]:
# make Background and Specialty columns look nice
df_decks = (df_decks.rename(columns={
  "background": "Background",
  "specialty": "Specialty",
}))
for col in ["Background", "Specialty"]:
  df_decks[col] = df_decks[col].apply(
    lambda s: s.replace('_', ' ').title()
  )

# initialize tables for export
tables = {}
for background in df_decks["Background"].unique():
  for specialty in df_decks["Specialty"].unique():
    bg_sp = f'{background}+{specialty}'
    tables[bg_sp] = {}

In [136]:
# score Background + Specialty combinations
df_background_specialty = group_and_score(df_decks,
  groupby_cols=["Background", "Specialty"],
  score_col="group_score",
  pack_index_col="deck_pack_index")
df_background_specialty = (df_background_specialty
  .drop(columns=["group_score", "pack_avg"])
  .rename(columns={"score": "Score"}
))
# save to export
tables['background_specialty'] = df_background_specialty.to_dict(orient='records')

print('Background + Specialty combination scores:')
df_background_specialty

Background + Specialty combination scores:

     Background       Specialty     Score
11     Shepherd     Conciliator  2.699273
22     Traveler        Explorer  2.288612
0       Artisan       Artificer  2.111409
18  Talespinner          Shaper  1.880108
23     Traveler          Shaper  1.434186
14     Shepherd  Spirit Speaker  1.405698
8       Forager          Shaper  1.403209
19  Talespinner  Spirit Speaker  1.327828
16  Talespinner     Conciliator  1.131234
7       Forager        Explorer  0.954841
17  Talespinner        Explorer  0.888299
13     Shepherd          Shaper  0.825041
24     Traveler  Spirit Speaker  0.800855
9       Forager  Spirit Speaker  0.798298
6       Forager     Conciliator  0.688548
12     Shepherd        Explorer  0.670139
21     Traveler     Conciliator  0.579437
20     Traveler       Artificer  0.495669
5       Forager       Artificer  0.439816
2       Artisan        Explorer  0.433616
3       Artisan          Shaper  0.425023
10     Shepherd       Artificer  0.369998
15  Talespinner       Artificer  0.297658
4       Artisan  Spirit Speaker  0.239115
1       Artisan     Conciliator  0.215681

Now we look at the cards chosen by decks in a specific Background and Specialty combination. We use the same function as above. We extracted `role_id` for each deck above. We want to score all versions of a card together, so we can either group by its `code` or `name`.

In [137]:
for background in df_background_specialty["Background"].unique():
  for specialty in df_background_specialty["Specialty"].unique():
    # we groupby code/role, not role_id
    df_decks["role"] = df_decks["role_id"].map(card_id_to_name)
    role_scores = group_and_score(
      df=df_decks,
      groupby_cols=["role"],
      score_col="group_score",
      pack_index_col="deck_pack_index",
      background=background,
      specialty=specialty
    )

    role_scores = (role_scores
      .drop(columns=["group_score", "pack_avg"])
      .rename(columns={
        "role": "Role",
        "score": "Score"
      }
    ))
    bg_sp = f'{background}+{specialty}'
    tables[bg_sp]['role'] = role_scores.to_dict(orient='records')

tables['Talespinner+Spirit Speaker']['role']

[{'Role': 'Keeper of the Grove', 'Score': 1.4597123366994063},
 {'Role': 'Cartographer of Many Worlds', 'Score': 0.9735440683483554},
 {'Role': 'Descendant of the Guide', 'Score': 0.5667435949522385}]

In [138]:
for background in df_background_specialty["Background"].unique():
  for specialty in df_background_specialty["Specialty"].unique():
    df_decks["equip_sum"] = df_decks["equip_sum"].astype(int)
    equip_scores = group_and_score(df_decks,
      groupby_cols=["equip_sum"],
      score_col="group_score",
      pack_index_col="deck_pack_index",
      background=background,
      specialty=specialty
    )
    equip_scores = (equip_scores
      .drop(columns=["group_score", "pack_avg"])
      .rename(columns={
        "equip_sum": "Total Equip",
        "score": "Score"
      }
    ))
    bg_sp = f'{background}+{specialty}'
    tables[bg_sp]['equip'] = equip_scores.to_dict(orient='records')

tables['Talespinner+Spirit Speaker']['equip']

[{'Total Equip': 5, 'Score': 3.49528285563689},
 {'Total Equip': 4, 'Score': 2.353773138740833},
 {'Total Equip': 2, 'Score': 1.2821035553398579},
 {'Total Equip': 3, 'Score': 0.7238655000377012},
 {'Total Equip': 6, 'Score': 0.6301992918971288},
 {'Total Equip': 7, 'Score': 0.24143201961094532},
 {'Total Equip': 1, 'Score': 0.12764647650279407},
 {'Total Equip': 0, 'Score': 0.11378554310815124},
 {'Total Equip': 9, 'Score': 0.031911619125698516}]

In [139]:
def score_aspect(background, specialty, aspect):
  aspect_scores = group_and_score(df_decks,
    groupby_cols=[aspect],
    score_col="group_score",
    pack_index_col="deck_pack_index",
    background=background,
    specialty=specialty
  )
  return aspect_scores

asp_to_aspect_lookup = {
  'awa': 'Awareness',
  'fit': 'Fitness',
  'foc': 'Focus',
  'spi': 'Spirit'
}

for background in df_background_specialty["Background"].unique():
  for specialty in df_background_specialty["Specialty"].unique():
    for asp, aspect in asp_to_aspect_lookup.items():
      df_aspect = score_aspect(background, specialty, asp)
      df_aspect = (df_aspect
        .drop(columns=["group_score", "pack_avg"])
        .rename(columns={
          asp: aspect,
          "score": "Score"
        }
      ))
      bg_sp = f'{background}+{specialty}'
      tables[bg_sp][aspect] = df_aspect.to_dict(orient='records')

tables['Talespinner+Spirit Speaker']['Awareness']

[{'Awareness': 1, 'Score': 2.707205570211743},
 {'Awareness': 2, 'Score': 0.8592603349592008},
 {'Awareness': 3, 'Score': 0.38296274233654526},
 {'Awareness': 4, 'Score': 0.05057135249251167}]

In [140]:
def extract_cards(background, specialty):
  score_col = "group_score"
  pack_index_col = "deck_pack_index"

  df = df_decks[
    (df_decks["Background"] == background)
    & (df_decks["Specialty"] == specialty)
    & (df_decks[score_col] > 0)
  ]

  # attach score and pack_index of deck to each card
  bg_sp_slots_data = []
  for _, deck in df.iterrows():
    slots = deck["slots"]
    for card_id, _ in slots.items():
      card_name = card_id_to_name[card_id]
      bg_sp_slots_data.append({
        "name": card_name,
        score_col: deck[score_col],
        pack_index_col: deck[pack_index_col]
      })

  # we don't need individual cards, just their sum
  bg_sp_slots_long = pd.DataFrame(bg_sp_slots_data)
  bg_sp_slots = (
    bg_sp_slots_long.groupby(["name", pack_index_col])
    [score_col].sum()
    .reset_index()
    .astype({pack_index_col: "Int64", score_col: "float64"})
  )

  # bg_sp_slots may not contain all allowed outside interest cards
  # get all cards that users can build their decks with
  available_cards = (df_cards[
    df_cards["supergroup_id"].isin(['Personality', 'Background', 'Specialty'])
      # & df_cards["is_latest"]
    ][["name", "supergroup_id", "subgroup_id"]]
    .drop_duplicates()
    .copy())
  # distinguish outside interest cards from background and specialty cards
  outside_interest_mask = (
    (available_cards["supergroup_id"] == 'Background')
      & (available_cards["subgroup_id"] != background)
    ) | (
    (available_cards["supergroup_id"] == 'Specialty')
      & (available_cards["subgroup_id"] != specialty))
  available_cards.loc[outside_interest_mask, "supergroup_id"] = 'Outside'
  available_cards.loc[outside_interest_mask, "subgroup_id"] = 'Interest'

  # join all cards with card data from decks
  bg_sp_cards = (available_cards
    .merge(
      bg_sp_slots,
      how='left',
      on="name")
    .astype({pack_index_col: "Int64", score_col: "float64"})
    .fillna(0)
  )
  return bg_sp_cards

In [141]:
def score_supergroup_subgroup(df, supergroup_id, subgroup_id):
  df = df[
    (df["supergroup_id"] == supergroup_id)
    & (df["subgroup_id"] == subgroup_id)
  ]
  group_scores = group_and_score(df,
    groupby_cols=["name"],
    score_col="group_score",
    pack_index_col="deck_pack_index"
  )
  return group_scores

df_card_lookup = df_cards[[
  "name",
  "equip",
  "level",
  "aspect_id"]].drop_duplicates()
assert df_card_lookup["name"].is_unique
df_card_lookup["equip"] = df_card_lookup["equip"].astype('Int64')
df_card_lookup["aspect_level"] = df_card_lookup.apply(
  lambda row: None if pd.isna(row["level"]) else f'{row["aspect_id"]} {int(row["level"])}',
  axis=1
)

for background in df_background_specialty["Background"].unique():
  for specialty in df_background_specialty["Specialty"].unique():
    bg_sp_cards = extract_cards(background, specialty)
    for supergroup_id, subgroup_id in [
        ('Personality', 'Awareness'),
        ('Personality', 'Fitness'),
        ('Personality', 'Focus'),
        ('Personality', 'Spirit'),
        ('Background', background),
        ('Specialty', specialty),
        ('Outside', 'Interest')]:
      df_group = score_supergroup_subgroup(bg_sp_cards, supergroup_id, subgroup_id)
      df_group = df_group.drop(columns=[
        "group_score",
        "pack_avg"
      ])
      if supergroup_id == 'Outside' and subgroup_id == 'Interest':
        df_group = df_group[df_group["score"] > 1]

      if supergroup_id == 'Personality':
        df_group = (df_group
          .merge(
            df_card_lookup[["name", "aspect_level"]],
            how="left",
            on="name"
          )
          .rename(columns={
            "name": "Name",
            "aspect_level": "Aspect requirement",
            "score": "Score"
          })
        )
        group_name = f'{supergroup_id}-{subgroup_id}'
      else:
        df_group = (df_group
          .merge(
            df_card_lookup[["name", "aspect_level", "equip"]],
            how="left",
            on="name"
          )
          .rename(columns={
            "name": "Name",
            "equip": "Equip value",
            "aspect_level": "Aspect requirement",
            "score": "Score"
          })
        )
        if supergroup_id == 'Outside' and subgroup_id == 'Interest':
          group_name = 'Outside Interest'
        else:
          group_name = supergroup_id

      bg_sp = f'{background}+{specialty}'
      tables[bg_sp][group_name] = df_group.to_dict(orient='records')
      print(f'\n{group_name}')
      print(df_group)

Personality-Awareness
         Name     Score Aspect requirement
0  Perceptive  1.971554              AWA 1
1  Insightful  1.094524              AWA 1
2    Thorough  0.890942              AWA 2
3   Dauntless  0.328018              AWA 1
4   Observant  0.243295              AWA 3
5    Vigilant  0.176897              AWA 1

Personality-Fitness
           Name     Score Aspect requirement
0          Bold  1.609393              FIT 2
1    Passionate  1.369809              FIT 1
2      Balanced  0.827828              FIT 1
3  Enthusiastic  0.818754              FIT 2
4     Steadfast  0.481693              FIT 3
5    Determined  0.258543              FIT 1

Personality-Focus
         Name     Score Aspect requirement
0   Versatile  1.474223              FOC 1
1  Deliberate  1.337577              FOC 1
2  Meticulous  1.225119              FOC 1
3      Astute  1.125115              FOC 2
4   Inventive  0.217729              FOC 1
5   Ingenious  0.212368              FOC 3

Personality-Spirit
            Name     Score Aspect requirement
0  Compassionate  1.869159              SPI 2
1       Engaging  1.509005              SPI 1
2    Magnanimous  1.319300              SPI 3
3     Thoughtful  0.436870              SPI 1
4       Sensible  0.235345              SPI 2
5     Persuasive  0.226712              SPI 1

Background
                      Name     Score Aspect requirement  Equip value
0        Oru the Sheep Dog  1.828851              SPI 2         <NA>
1            Healing Touch  1.687289              SPI 1         <NA>
2      Paratrepsis Whistle  1.407140              FOC 1            1
3           Homeward Bound  1.340538              FIT 2         <NA>
4    Riri the Sparrow Hawk  1.206512              AWA 2         <NA>
5      Zoological Recorder  1.151350              FOC 1            1
6         Piercing Whistle  1.062508              AWA 1         <NA>
7         Calming Presence  0.895606              SPI 1         <NA>
8      A Deeper Connection  0.714906              SPI 1         <NA>
9    Essays on Shepherding  0.438831              FIT 2            1
10            One Eye Open  0.289856              AWA 1         <NA>
11  A Deeper Understanding  0.206450              FOC 2         <NA>
12          A Gentle Nudge  0.199260              FIT 1         <NA>

Specialty
                    Name     Score Aspect requirement  Equip value
0      Pokodo the Ferret  2.351795              SPI 2         <NA>
1   Intention Translator  2.128493              FOC 1            2
2    Follow in Footsteps  2.041985              FIT 1         <NA>
3          A Dear Friend  1.482675              SPI 3         <NA>
4          Surveyed Land  1.319023              AWA 1         <NA>
5      Empathy Amplifier  1.235107              SPI 1            2
6    Ancestral Teachings  0.792518              SPI 1         <NA>
7                Tracked  0.633633              FIT 3         <NA>
8          Orlin Thumper  0.629144              FIT 2            1
9       All Together Now  0.590619              FIT 2         <NA>
10        Tranquilisnare  0.501608              AWA 2         <NA>
11           Influential  0.390925              FOC 1         <NA>
12          Show No Fear  0.327300              AWA 2         <NA>
13             Safeguard  0.127078              FOC 2         <NA>
14       One With Nature  0.085818              AWA 3         <NA>
15     Nidocyte Sentinel  0.058016              FOC 3         <NA>

Outside Interest
                         Name      Score Aspect requirement  Equip value
0                   Trail Mix  17.682581              FIT 2            2
1    Energized Hiking Greaves  16.434192              SPI 2            2
2            Infusion Canteen   7.486159              FOC 1            2
3           Meditation Pillow   5.869812              SPI 2            2
4            Toro the Raccoon   5.695277              FIT 2         <NA>
5        Cradled by the Earth   3.803783              SPI 3         <NA>
6         Thoroughly Prepared   2.439385              SPI 3         <NA>
7             Boundary Sensor   2.289005              FIT 1            2
8       Nut-rolled Honey Loaf   2.235787              SPI 1            2
9   The Stouthearted Guardian   2.083656              SPI 2         <NA>
10                  Eagle Eye   1.864437              AWA 1         <NA>
11             Ironwool Boots   1.807815              SPI 1            1
12              Favorite Gear   1.622974              SPI 1         <NA>
13            Familiar Ground   1.320040              FIT 1         <NA>
14           Remote Sentinels   1.289987              SPI 2            1
15               Walk With Me   1.288362              SPI 1         <NA>
16        Spirit of Mount Nim   1.281913              FIT 3         <NA>
17       Wrist-mounted Darter   1.239780              FIT 3            2
18              Trail Markers   1.069530              FIT 1         <NA>
19        Hush Little Critter   1.042692              AWA 1         <NA>
20                    Strider   1.008261              FIT 1         <NA>

Personality-Awareness
         Name     Score Aspect requirement
0  Perceptive  1.287945              AWA 1
1    Thorough  1.196912              AWA 2
2  Insightful  1.136950              AWA 1
3   Dauntless  0.652944              AWA 1
4   Observant  0.610463              AWA 3
5    Vigilant  0.467770              AWA 1

Personality-Fitness
           Name     Score Aspect requirement
0          Bold  1.869969              FIT 2
1      Balanced  0.947551              FIT 1
2    Determined  0.809198              FIT 1
3  Enthusiastic  0.603558              FIT 2
4    Passionate  0.519281              FIT 1
5     Steadfast  0.195883              FIT 3

Personality-Focus
         Name     Score Aspect requirement
0   Versatile  1.880173              FOC 1
1  Deliberate  1.487900              FOC 1
2  Meticulous  0.842901              FOC 1
3   Inventive  0.666534              FOC 1
4      Astute  0.636452              FOC 2
5   Ingenious  0.297802              FOC 3

Personality-Spirit
            Name     Score Aspect requirement
0  Compassionate  1.863843              SPI 2
1     Thoughtful  1.332649              SPI 1
2     Persuasive  1.008978              SPI 1
3       Engaging  0.732232              SPI 1
4    Magnanimous  0.362285              SPI 3
5       Sensible  0.000000              SPI 2

Background
                      Name     Score Aspect requirement  Equip value
0        Oru the Sheep Dog  1.552606              SPI 2         <NA>
1    Riri the Sparrow Hawk  1.487350              AWA 2         <NA>
2            Healing Touch  1.460676              SPI 1         <NA>
3      Paratrepsis Whistle  1.388062              FOC 1            1
4      Zoological Recorder  1.321495              FOC 1            1
5           Homeward Bound  1.210899              FIT 2         <NA>
6         Piercing Whistle  1.048704              AWA 1         <NA>
7             One Eye Open  0.634538              AWA 1         <NA>
8         Calming Presence  0.622847              SPI 1         <NA>
9    Essays on Shepherding  0.573687              FIT 2            1
10     A Deeper Connection  0.522629              SPI 1         <NA>
11          A Gentle Nudge  0.385190              FIT 1         <NA>
12  A Deeper Understanding  0.324793              FOC 2         <NA>

Specialty
                             Name     Score Aspect requirement  Equip value
0                    Walk With Me  2.095322              SPI 1         <NA>
1            A Leaf in the Breeze  1.785323              AWA 1         <NA>
2                 Boundary Sensor  1.670698              FIT 1            2
3              Orlin Hiking Stave  1.491456              FIT 2            2
4                Toro the Raccoon  1.470009              FIT 2         <NA>
5             Phonoscopic Headset  1.357956              FOC 1            1
6           Nut-rolled Honey Loaf  0.983214              SPI 1            2
7              A Circuitous Route  0.811258              AWA 1         <NA>
8               Hydrolens Goggles  0.661035              AWA 2            1
9                   Field Journal  0.623457              FOC 2            2
10           Cradled by the Earth  0.598808              SPI 3         <NA>
11                Breathe Into It  0.596378              SPI 2         <NA>
12             Afforded by Nature  0.588162              FIT 3         <NA>
13  Share in the Valley’s Secrets  0.375751              AWA 3         <NA>
14                   Hidden Trail  0.242909              FOC 3         <NA>
15            Personal Travelogue  0.088794              FOC 2            2

Outside Interest
                         Name      Score Aspect requirement  Equip value
0           Pokodo the Ferret  12.293403              SPI 2         <NA>
1            Infusion Canteen   4.537621              FOC 1            2
2                   Eagle Eye   4.341191              AWA 1         <NA>
3               Trail Markers   4.211270              FIT 1         <NA>
4              Ironwool Boots   4.185876              SPI 1            1
5         Thoroughly Prepared   3.563490              SPI 3         <NA>
6          Nature's Abundance   2.915583              SPI 1         <NA>
7                     Strider   2.915583              FIT 1         <NA>
8    Energized Hiking Greaves   2.915583              SPI 2            2
9               Favorite Gear   2.892968              SPI 1         <NA>
10                  Trail Mix   2.763174              FIT 2            2
11       Wrist-mounted Darter   2.429652              FIT 3            2
12            Familiar Ground   2.229434              FIT 1         <NA>
13      Memlev Trekking Poles   2.186687              FOC 3            3
14        Pocketed Belt Pouch   2.080694              AWA 2            1
15        Follow in Footsteps   2.047439              FIT 1         <NA>
16         Carbonforged Cable   1.973319              AWA 2         <NA>
17      Universal Power Cells   1.943722              FOC 1            1
18       The Tireless Artisan   1.868920              SPI 1         <NA>
19                  Dayhowler   1.516986              AWA 3            1
20      Moment of Desperation   1.457791              FIT 1         <NA>
21  Paths We’ve Roamed Before   1.457791              AWA 2         <NA>
22        Adaptable Multitool   1.457791              FOC 2            2
23         Loose-Leaf Tea Kit   1.457791              FOC 2            2
24       Intention Translator   1.228464              FOC 1            2
25                  Ferinodex   1.214826              AWA 1            2
26            Camoweave Cloak   1.214826              SPI 2            1
27              Orlin Thumper   1.214826              FIT 2            1

Personality-Awareness
         Name     Score Aspect requirement
0    Thorough  1.684989              AWA 2
1  Perceptive  1.660330              AWA 1
2    Vigilant  1.075890              AWA 1
3  Insightful  0.561845              AWA 1
4   Dauntless  0.185360              AWA 1
5   Observant  0.000000              AWA 3

Personality-Fitness
           Name     Score Aspect requirement
0      Balanced  1.978730              FIT 1
1          Bold  1.366045              FIT 2
2     Steadfast  1.365260              FIT 3
3    Passionate  0.840158              FIT 1
4    Determined  0.690248              FIT 1
5  Enthusiastic  0.000000              FIT 2

Personality-Focus
         Name     Score Aspect requirement
0   Versatile  1.754829              FOC 1
1   Ingenious  0.916824              FOC 3
2      Astute  0.862308              FOC 2
3  Meticulous  0.765323              FOC 1
4  Deliberate  0.694392              FOC 1
5   Inventive  0.641981              FOC 1

Personality-Spirit
            Name     Score Aspect requirement
0  Compassionate  1.649356              SPI 2
1       Engaging  1.233889              SPI 1
2     Persuasive  1.223582              SPI 1
3     Thoughtful  0.882133              SPI 1
4       Sensible  0.332704              SPI 2
5    Magnanimous  0.000000              SPI 3

Background
                      Name     Score Aspect requirement  Equip value
0            Healing Touch  1.548788              SPI 1         <NA>
1        Oru the Sheep Dog  1.548788              SPI 2         <NA>
2         Piercing Whistle  1.372904              AWA 1         <NA>
3      Paratrepsis Whistle  1.227361              FOC 1            1
4    Riri the Sparrow Hawk  1.213900              AWA 2         <NA>
5      Zoological Recorder  0.949676              FOC 1            1
6           Homeward Bound  0.933139              FIT 2         <NA>
7         Calming Presence  0.904608              SPI 1         <NA>
8      A Deeper Connection  0.782839              SPI 1         <NA>
9             One Eye Open  0.681951              AWA 1         <NA>
10          A Gentle Nudge  0.516156              FIT 1         <NA>
11   Essays on Shepherding  0.493678              FIT 2            1
12  A Deeper Understanding  0.451381              FOC 2         <NA>

Specialty
                       Name     Score Aspect requirement  Equip value
0          Infusion Canteen  2.159618              FOC 1            2
1      A Stone in the River  1.585971              SPI 1         <NA>
2                  Creative  1.362739              AWA 2         <NA>
3             Trail Markers  1.255318              FIT 1         <NA>
4        Carbonforged Cable  1.243491              AWA 2         <NA>
5                 Ferinodex  1.189345              AWA 1            2
6           Camoweave Cloak  1.148988              SPI 2            1
7          Remote Sentinels  1.111027              SPI 2            1
8          Spiderpad Gloves  0.908807              FIT 2            2
9        Memorill Sketchpad  0.644814              FOC 2            2
10                Dayhowler  0.582130              AWA 3            1
11     Wrist-mounted Darter  0.532282              FIT 3            2
12      Thoroughly Prepared  0.451513              SPI 3         <NA>
13  Carbonforged Theodolite  0.384794              FIT 1            2
14    Memlev Trekking Poles  0.369049              FOC 3            3
15      Power Cell Recycler  0.118630              FOC 1            1

Outside Interest
                             Name      Score Aspect requirement  Equip value
0             Ancestral Teachings  14.119706              SPI 1         <NA>
1             Pocketed Belt Pouch   6.587636              AWA 2            1
2            Intention Translator   4.395675              FOC 1            2
3               Pokodo the Ferret   4.069538              SPI 2         <NA>
4                  The Right Tool   3.839742              AWA 1         <NA>
5                         Tracked   3.730726              FIT 3         <NA>
6                 Familiar Ground   3.516540              FIT 1         <NA>
7                         Strider   3.516540              FIT 1         <NA>
8                   Favorite Gear   3.460389              SPI 1         <NA>
9               Meditation Pillow   3.223495              SPI 2            2
10                Boundary Sensor   2.637405              FIT 1            2
11           A Leaf in the Breeze   2.637405              AWA 1         <NA>
12            Phonoscopic Headset   2.637405              FOC 1            1
13                   Walk With Me   1.865363              SPI 1         <NA>
14      Paths We’ve Roamed Before   1.865363              AWA 2         <NA>
15                   Hidden Trail   1.758270              FOC 3         <NA>
16            Carbonforged Trowel   1.758270              FIT 2            2
17           Cradled by the Earth   1.758270              SPI 3         <NA>
18             Loose-Leaf Tea Kit   1.758270              FOC 2            2
19            Adaptable Multitool   1.758270              FOC 2            2
20             Functional Replica   1.758270              FOC 2            2
21                      Trail Mix   1.758270              FIT 2            2
22  Share in the Valley’s Secrets   1.758270              AWA 3         <NA>
23                  Orlin Thumper   1.758270              FIT 2            1
24       Featherweight Gauzeweave   1.708884              SPI 1         <NA>
25               Toro the Raccoon   1.334592              FIT 2         <NA>
26             Orlin Hiking Stave   1.310722              FIT 2            2

Personality-Awareness
         Name     Score Aspect requirement
0  Perceptive  1.756242              AWA 1
1    Thorough  1.112347              AWA 2
2   Dauntless  0.932785              AWA 1
3  Insightful  0.755563              AWA 1
4    Vigilant  0.456141              AWA 1
5   Observant  0.257433              AWA 3

Personality-Fitness
           Name     Score Aspect requirement
0          Bold  1.799023              FIT 2
1     Steadfast  1.045412              FIT 3
2      Balanced  0.920010              FIT 1
3    Passionate  0.899705              FIT 1
4  Enthusiastic  0.612544              FIT 2
5    Determined  0.415176              FIT 1

Personality-Focus
         Name     Score Aspect requirement
0   Versatile  1.626762              FOC 1
1  Deliberate  1.624363              FOC 1
2  Meticulous  1.125188              FOC 1
3      Astute  0.705859              FOC 2
4   Inventive  0.553911              FOC 1
5   Ingenious  0.257433              FOC 3

Personality-Spirit
            Name     Score Aspect requirement
0  Compassionate  2.227255              SPI 2
1    Magnanimous  1.029322              SPI 3
2       Engaging  0.912098              SPI 1
3     Thoughtful  0.625146              SPI 1
4     Persuasive  0.318983              SPI 1
5       Sensible  0.128717              SPI 2

Background
                      Name     Score Aspect requirement  Equip value
0        Oru the Sheep Dog  1.652509              SPI 2         <NA>
1            Healing Touch  1.642312              SPI 1         <NA>
2    Riri the Sparrow Hawk  1.420479              AWA 2         <NA>
3      Paratrepsis Whistle  1.364676              FOC 1            1
4      Zoological Recorder  1.154939              FOC 1            1
5           Homeward Bound  1.144230              FIT 2         <NA>
6         Piercing Whistle  0.847452              AWA 1         <NA>
7         Calming Presence  0.652626              SPI 1         <NA>
8    Essays on Shepherding  0.541891              FIT 2            1
9             One Eye Open  0.499603              AWA 1         <NA>
10  A Deeper Understanding  0.441643              FOC 2         <NA>
11          A Gentle Nudge  0.304513              FIT 1         <NA>
12     A Deeper Connection  0.263083              SPI 1         <NA>

Specialty
                             Name     Score Aspect requirement  Equip value
0             Seen Through Cycles  1.789839              SPI 2         <NA>
1                  Throng of Life  1.671240              FOC 1         <NA>
2                 Shape the Earth  1.596505              FIT 2         <NA>
3                        Sky Whip  1.455921              AWA 2         <NA>
4              Scepter of Harmony  1.278921              SPI 3            2
5   Visions of the Floating Tower  1.267580              SPI 2            1
6                       Slow Time  1.226867              AWA 1         <NA>
7                       Harmonize  1.144179              SPI 1         <NA>
8                      Root Snare  0.894428              AWA 1         <NA>
9                     Novice Lens  0.621102              FOC 2            1
10          Staff of the Wanderer  0.563789              FIT 3            2
11                      Conductor  0.530143              FOC 2         <NA>
12           What Should Never Be  0.448009              FIT 1         <NA>
13              Rod of the Clouds  0.319899              FOC 3            2

In [142]:
with open('project/fifteen_good_cards.json', 'w') as f:
  json.dump(tables, f)

-- OLD STUFF --

For the actual deck, we labeled each card by `supergroup_id` and `subgroup_id` above. This splits available cards into seven groups, which we score separately: four aspects of Personality cards, their Background, their Specialty, and their Outside Interest.

In [ ]:
def score_background_specialty(background, specialty, score_col, pack_index_col):
  bg_sp_decks = df_decks[(df_decks["background"] == background)
    & (df_decks["specialty"] == specialty)
    & (df_decks[score_col] > 0)].copy()

  bg_sp_decks["role"] = bg_sp_decks["role_id"].map(card_id_to_name)
  print('Role scores:')
  group_and_score_wrapper(bg_sp_decks, "role", score_col, pack_index_col)

  bg_sp_cards = extract_cards(bg_sp_decks, score_col, pack_index_col)

  build_order = [('Personality', 'Awareness', 3),
                ('Personality', 'Fitness', 3),
                ('Personality', 'Focus', 3),
                ('Personality', 'Spirit', 3),
                ('Background', background.capitalize(), 10),
                ('Specialty', specialty.capitalize(), 10),
                ('Outside', 'Interest', 10)]

  for supergroup_id, subgroup_id, num_results in build_order:
    build_cards = (bg_sp_cards[
      (bg_sp_cards["supergroup_id"] == supergroup_id)
      & (bg_sp_cards["subgroup_id"] == subgroup_id)]
      .copy())
      
    print(f'\n{supergroup_id} {subgroup_id} scores:')
    group_and_score_wrapper(build_cards, "name", score_col, pack_index_col,
      num_results)

background = 'shepherd'
specialty = 'conciliator'
score_background_specialty(background, specialty,
  score_col="group_score",
  pack_index_col="deck_pack_index")

Role scores:
Name                                Group  / Avg    = Score
------------------------------------------------------------
Voice of the Elders                 497.2  / 401.7  = 1.238
Guardian                            314.6  / 401.7  = 0.783
Pathwarden                          19.7   / 28.0   = 0.702

Personality Awareness scores:
Name                                Group  / Avg    = Score
------------------------------------------------------------
Perceptive                          398.4  / 200.9  = 1.983
Insightful                          212.3  / 200.9  = 1.057
Thorough                            175.7  / 200.9  = 0.875

Personality Fitness scores:
Name                                Group  / Avg    = Score
------------------------------------------------------------
Bold                                317.9  / 200.9  = 1.583
Passionate                          277.2  / 200.9  = 1.380
Balanced                            167.2  / 200.9  = 0.833

Personality Focus scores:
Name                                Group  / Avg    = Score
------------------------------------------------------------
Versatile                           303.6  / 200.9  = 1.511
Deliberate                          20.8   / 14.0   = 1.482
Meticulous                          229.3  / 200.9  = 1.142

Personality Spirit scores:
Name                                Group  / Avg    = Score
------------------------------------------------------------
Compassionate                       365.0  / 200.9  = 1.817
Engaging                            306.2  / 200.9  = 1.525
Magnanimous                         21.0   / 14.0   = 1.497

Background Shepherd scores:
Name                                Group  / Avg    = Score
------------------------------------------------------------
Oru the Sheep Dog                   812.3  / 449.0  = 1.809
Healing Touch                       752.1  / 449.0  = 1.675
Paratrepsis Whistle                 637.4  / 449.0  = 1.420
Homeward Bound                      597.1  / 449.0  = 1.330
Zoological Recorder                 42.2   / 32.5   = 1.299
Riri the Sparrow Hawk               532.3  / 449.0  = 1.186
Piercing Whistle                    32.5   / 32.5   = 0.999
Calming Presence                    394.3  / 449.0  = 0.878
A Deeper Connection                 21.2   / 32.5   = 0.652
Essays on Shepherding               16.9   / 32.5   = 0.520

Specialty Conciliator scores:
Name                                Group  / Avg    = Score
------------------------------------------------------------
Pokodo the Ferret                   788.9  / 338.5  = 2.330
Intention Translator                707.6  / 338.5  = 2.090
Follow in Footsteps                 684.8  / 338.5  = 2.023
A Dear Friend                       509.8  / 338.5  = 1.506
Surveyed Land                       455.3  / 338.5  = 1.345
Empathy Amplifier                   33.0   / 26.4   = 1.250
Ancestral Teachings                 280.6  / 338.5  = 0.829
All Together Now                    16.7   / 26.4   = 0.631
Orlin Thumper                       206.9  / 338.5  = 0.611
Tracked                             201.2  / 338.5  = 0.594

Outside Interest scores:
Name                                Group  / Avg    = Score
------------------------------------------------------------
Trail Mix                           161.8  / 9.3    = 17.410
Energized Hiking Greaves            158.0  / 9.3    = 16.996
Infusion Canteen                    72.2   / 9.3    = 7.772
Toro the Raccoon                    9.3    / 1.8    = 5.153
Meditation Pillow                   45.8   / 9.3    = 4.923
Cradled by the Earth                41.0   / 9.3    = 4.409
Thoroughly Prepared                 26.8   / 9.3    = 2.879
Ironwool Boots                      19.7   / 7.5    = 2.631
Boundary Sensor                     23.0   / 9.3    = 2.475
The Stouthearted Guardian           3.9    / 1.8    = 2.155

In [125]:
background = 'traveler'
specialty = 'artificer'
score_background_specialty(background, specialty,
  score_col="group_score",
  pack_index_col="deck_pack_index")

Role scores:
Name                                Group  / Avg    = Score
------------------------------------------------------------
Exceptional Tinkerer                125.8  / 74.3   = 1.695
Gregarious Inventor                 4.6    / 7.7    = 0.593
Masterful Engineer                  25.8   / 74.3   = 0.347

Personality Awareness scores:
Name                                Group  / Avg    = Score
------------------------------------------------------------
Thorough                            64.9   / 32.4   = 2.004
Perceptive                          53.8   / 32.4   = 1.660
Insightful                          19.8   / 32.4   = 0.612

Personality Fitness scores:
Name                                Group  / Avg    = Score
------------------------------------------------------------
Balanced                            50.4   / 37.1   = 1.358
Passionate                          48.8   / 37.1   = 1.316
Steadfast                           4.1    / 3.9    = 1.061

Personality Focus scores:
Name                                Group  / Avg    = Score
------------------------------------------------------------
Versatile                           63.0   / 37.1   = 1.696
Astute                              45.0   / 37.1   = 1.211
Inventive                           26.5   / 37.1   = 0.713

Personality Spirit scores:
Name                                Group  / Avg    = Score
------------------------------------------------------------
Compassionate                       59.9   / 37.1   = 1.613
Thoughtful                          34.4   / 37.1   = 0.926
Persuasive                          33.7   / 37.1   = 0.907

Background Traveler scores:
Name                                Group  / Avg    = Score
------------------------------------------------------------
Eagle Eye                           119.4  / 76.6   = 1.558
Strider                             114.0  / 76.6   = 1.487
Reverb Locket                       109.3  / 76.6   = 1.426
Paths We’ve Roamed Before           95.6   / 76.6   = 1.247
Perfect Recall                      92.8   / 76.6   = 1.211
Ironwool Boots                      84.7   / 76.6   = 1.105
Adaptable Multitool                 59.5   / 76.6   = 0.777
Grell's Secret Map                  6.8    / 9.7    = 0.703
Trail Mix                           50.8   / 76.6   = 0.663
Meditation Pillow                   43.8   / 76.6   = 0.572

Specialty Artificer scores:
Name                                Group  / Avg    = Score
------------------------------------------------------------
Trail Markers                       123.8  / 62.7   = 1.974
A Stone in the River                114.7  / 62.7   = 1.830
Infusion Canteen                    112.4  / 62.7   = 1.793
Creative                            10.9   / 7.2    = 1.511
Carbonforged Cable                  70.4   / 62.7   = 1.123
Memorill Sketchpad                  64.5   / 62.7   = 1.030
Camoweave Cloak                     55.1   / 62.7   = 0.878
Ferinodex                           54.8   / 62.7   = 0.874
Power Cell Recycler                 5.2    / 7.2    = 0.714
Memlev Trekking Poles               44.3   / 62.7   = 0.707

Outside Interest scores:
Name                                Group  / Avg    = Score
------------------------------------------------------------
Pocketed Belt Pouch                 32.2   / 2.8    = 11.433
Pokodo the Ferret                   11.5   / 1.1    = 9.995
Moment of Desperation               7.3    / 1.1    = 6.397
Walk With Me                        15.7   / 2.8    = 5.580
Hidden Trail                        4.4    / 1.1    = 3.865
The Right Tool                      4.4    / 1.1    = 3.865
Favorite Gear                       9.9    / 2.8    = 3.526
A Leaf in the Breeze                4.0    / 1.1    = 3.465
Universal Power Cells               3.9    / 1.1    = 3.398
Cradled by the Earth                3.5    / 1.1    = 3.065

In [22]:
df_decks.columns

Index(['id', 'user_id', 'slots', 'side_slots', 'extra_slots', 'version',
       'name', 'description', 'awa', 'spi', 'fit', 'foc', 'created_at',
       'updated_at', 'meta', 'user', 'taboo_set_id', 'published',
       'previous_deck', 'next_deck', 'copy_count', 'comment_count',
       'like_count', 'liked_by_user', 'original_deck', 'campaign', 'comments',
       'background', 'specialty', 'role_id', 'is_ignore', 'deck_pack_index',
       'has_15_cards', 'has_spoiler', 'is_latest', 'all_decks_parent_id',
       'parent_id', 'inspiration_id', 'user_weight', 'deck_weight',
       'taboo_weight', 'group_score'],
      dtype='object')

In [27]:
for aspect in ['awa', 'fit', 'foc', 'spi']:
  sums = (
    df_decks.groupby(["background", "specialty", aspect], as_index=False)["deck_weight"]
    .sum()
  )
  top = (
    sums.sort_values("deck_weight", ascending=False)
    .drop_duplicates(["background", "specialty"])
  )
  pivot = top.pivot(index="background", columns="specialty", values=aspect)
  print(f"\nMost common {aspect}:")
  print(pivot)

Most common awa:
specialty    artificer  conciliator  explorer  shaper  spirit_speaker
background
artisan              2            2         2       2               2
forager              2            2         2       3               1
shepherd             2            2         2       2               1
talespinner          2            2         1       1               1
traveler             2            2         2       2               1

Most common fit:
specialty    artificer  conciliator  explorer  shaper  spirit_speaker
background
artisan              1            2         2       2               2
forager              2            2         2       2               2
shepherd             2            2         2       2               2
talespinner          1            1         2       2               2
traveler             2            2         3       3               2

Most common foc:
specialty    artificer  conciliator  explorer  shaper  spirit_speaker
background
artisan              3            2         3       2               3
forager              2            2         2       2               2
shepherd             1            1         1       1               3
talespinner          1            2         2       2               3
traveler             2            1         1       1               2

Most common spi:
specialty    artificer  conciliator  explorer  shaper  spirit_speaker
background
artisan              2            2         1       2               2
forager              2            3         2       2               2
shepherd             2            3         2       3               2
talespinner          2            3         2       2               2
traveler             2            3         2       2               2